---
- name: Install MySQL
  apt: pkg={{item}} state=installed
  with_items:
    - mysql-server
    - python-mysqldb

- name: Update MySQL root password
  mysql_user: name=root host={{item}} password={{mysql_password}}
  with_items:
    - "{{ ansible_hostname }}"
    - "{{ ansible_eth0.ipv4.address }}"
    - '127.0.0.1'
    - '::1'
    - localhost