---
- name: Add New Relic repository
  sudo_user: root
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present
  register: new_relic_apt

- name: Add New Relic PPG Key
  sudo_user: root
  apt_key: url=https://download.newrelic.com/548C16BF.gpg 
  register: new_relic_ppg

- name: Update APT cache
  apt: update_cache=yes
  register: update_cache

- name: Install New Relic
  sudo_user: root
  when: new_relic_apt|success and new_relic_ppg|success and update_cache|success
  apt: pkg=newrelic-sysmond state=installed
  register: new_relic

- name: Configure New Relic
  sudo_user: root
  when: new_relic|success
  shell: nrsysmond-config --set license_key={{ license_key }}
  notify:
    - Start NewRelic
